version: 0.1

phases:
  build:
    commands:
      - echo "Execute maven test"
      - mvn test
  post_build:
    commands:
      - echo "Execute maven package"
      - mvn package
artifacts:
  files:
    - target/MotorVehicles-jar-with-dependencies.jar
    - docker/buildspec.yml
    - docker/Dockerfile
  discard-paths: yes
