version: 0.1

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "Docker build"
      - docker build -t $IMAGE_TAG .
      - echo "Docker tag"
      - docker tag $IMAGE_TAG:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_TAG:latest
  post_build:
    commands:
      - echo "Docker push"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_TAG:latest
