version: 0.1

phases:
  build:
    commands:
      - echo "Start command 1"
      - echo "Start command 2"
  post_build:
    commands:
      - echo "Start command 3"
      - echo "Start command 4"
artifacts:
  files:
    - target/MotorVehicles-jar-with-dependencies.jar
    - docker/buildspec.yml
    - docker/Dockerfile
  discard-paths: yes
